framework:
  http_client:
    scoped_clients:
      gharchive.client:
        base_uri: 'https://data.gharchive.org'

when@test:
  framework:
    http_client:
      mock_response_factory: App\Tests\Func\MockGHArchiveClientCallback
