framework:
  messenger:
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'
    routing:
      'App\Message\BatchEvents': async

when@test:
  framework:
    messenger:
      transports:
        sync: 'sync://'
      routing:
        'App\Message\BatchEvents': sync
